title: Learning Artificial Intelligence
email: pcoady@alum.mit.edu
author: Patrick Coady
description: My journey from IC designer to AI designer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://learningai.io/"
github_username: pat-coady
gist_username: pat-coady
twitter_username: CoadyPatrick
linkedin_username: patrick-coady-76995823
disqus:
    shortname: http-learningai-io

google_analytics: UA-96364586-1

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
